services:
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      timeout: 1s
      retries: 3
    volumes:
    - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata: